name: visualSA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1133
title: Photography portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050608'
    - '#871a1d'
    - '#817833'
    - '#e2c59b'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
