name: visualSA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36205684719607234
title: Photography portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050608'
    - '#871a1d'
    - '#817833'
    - '#e2c59b'
  brandStrength: 0.9375
  lightness: 0.9840142834000289
  saturation: 0.8970892855431885
  rhythmicContrast: 0.36957257706671953
purpose: []
